'use client';

export const ALTERNATE_UI_URL = 'https://trivalleyclinic.com';
export const SEO_IMAGE = '/logo/solicators.png';
export const countryFlags: Record<string, string> = {
  India: 'https://flagcdn.com/w320/in.png',
  USA: 'https://flagcdn.com/w320/us.png',
  UK: 'https://flagcdn.com/w320/gb.png',
  Canada: 'https://flagcdn.com/w320/ca.png',
  Australia: 'https://flagcdn.com/w320/au.png',

  Germany: 'https://flagcdn.com/w320/de.png',
  France: 'https://flagcdn.com/w320/fr.png',
  Italy: 'https://flagcdn.com/w320/it.png',
  Spain: 'https://flagcdn.com/w320/es.png',
  Netherlands: 'https://flagcdn.com/w320/nl.png',

  Singapore: 'https://flagcdn.com/w320/sg.png',
  UnitedArabEmirates: 'https://flagcdn.com/w320/ae.png',
  SaudiArabia: 'https://flagcdn.com/w320/sa.png',
  Japan: 'https://flagcdn.com/w320/jp.png',
  China: 'https://flagcdn.com/w320/cn.png',

  SouthKorea: 'https://flagcdn.com/w320/kr.png',
  Brazil: 'https://flagcdn.com/w320/br.png',
  SouthAfrica: 'https://flagcdn.com/w320/za.png',
  Russia: 'https://flagcdn.com/w320/ru.png',
  Mexico: 'https://flagcdn.com/w320/mx.png',
};
export const COUNTRIES = [
  { countryName: 'Afghanistan', code: '+93' },
  { countryName: 'Albania', code: '+355' },
  { countryName: 'Algeria', code: '+213' },
  { countryName: 'Andorra', code: '+376' },
  { countryName: 'Angola', code: '+244' },
  { countryName: 'Antigua and Barbuda', code: '+1-268' },
  { countryName: 'Argentina', code: '+54' },
  { countryName: 'Armenia', code: '+374' },
  { countryName: 'Australia', code: '+61' },
  { countryName: 'Austria', code: '+43' },
  { countryName: 'Azerbaijan', code: '+994' },
  { countryName: 'Bahamas', code: '+1-242' },
  { countryName: 'Bahrain', code: '+973' },
  { countryName: 'Bangladesh', code: '+880' },
  { countryName: 'Barbados', code: '+1-246' },
  { countryName: 'Belarus', code: '+375' },
  { countryName: 'Belgium', code: '+32' },
  { countryName: 'Belize', code: '+501' },
  { countryName: 'Benin', code: '+229' },
  { countryName: 'Bhutan', code: '+975' },
  { countryName: 'Bolivia', code: '+591' },
  { countryName: 'Bosnia and Herzegovina', code: '+387' },
  { countryName: 'Botswana', code: '+267' },
  { countryName: 'Brazil', code: '+55' },
  { countryName: 'Brunei', code: '+673' },
  { countryName: 'Bulgaria', code: '+359' },
  { countryName: 'Burkina Faso', code: '+226' },
  { countryName: 'Burundi', code: '+257' },
  { countryName: 'Cabo Verde', code: '+238' },
  { countryName: 'Cambodia', code: '+855' },
  { countryName: 'Cameroon', code: '+237' },
  { countryName: 'Canada', code: '+1' },
  { countryName: 'Central African Republic', code: '+236' },
  { countryName: 'Chad', code: '+235' },
  { countryName: 'Chile', code: '+56' },
  { countryName: 'China', code: '+86' },
  { countryName: 'Colombia', code: '+57' },
  { countryName: 'Comoros', code: '+269' },
  { countryName: 'Congo (Congo-Brazzaville)', code: '+242' },
  { countryName: 'Costa Rica', code: '+506' },
  { countryName: 'Croatia', code: '+385' },
  { countryName: 'Cuba', code: '+53' },
  { countryName: 'Cyprus', code: '+357' },
  { countryName: 'Czech Republic', code: '+420' },
  { countryName: 'Democratic Republic of the Congo', code: '+243' },
  { countryName: 'Denmark', code: '+45' },
  { countryName: 'Djibouti', code: '+253' },
  { countryName: 'Dominica', code: '+1-767' },
  { countryName: 'Dominican Republic', code: '+1-809' },
  { countryName: 'Ecuador', code: '+593' },
  { countryName: 'Egypt', code: '+20' },
  { countryName: 'El Salvador', code: '+503' },
  { countryName: 'Equatorial Guinea', code: '+240' },
  { countryName: 'Eritrea', code: '+291' },
  { countryName: 'Estonia', code: '+372' },
  { countryName: 'Eswatini', code: '+268' },
  { countryName: 'Ethiopia', code: '+251' },
  { countryName: 'Fiji', code: '+679' },
  { countryName: 'Finland', code: '+358' },
  { countryName: 'France', code: '+33' },
  { countryName: 'Gabon', code: '+241' },
  { countryName: 'Gambia', code: '+220' },
  { countryName: 'Georgia', code: '+995' },
  { countryName: 'Germany', code: '+49' },
  { countryName: 'Ghana', code: '+233' },
  { countryName: 'Greece', code: '+30' },
  { countryName: 'Grenada', code: '+1-473' },
  { countryName: 'Guatemala', code: '+502' },
  { countryName: 'Guinea', code: '+224' },
  { countryName: 'Guinea-Bissau', code: '+245' },
  { countryName: 'Guyana', code: '+592' },
  { countryName: 'Haiti', code: '+509' },
  { countryName: 'Honduras', code: '+504' },
  { countryName: 'Hungary', code: '+36' },
  { countryName: 'Iceland', code: '+354' },
  { countryName: 'India', code: '+91' },
  { countryName: 'Indonesia', code: '+62' },
  { countryName: 'Iran', code: '+98' },
  { countryName: 'Iraq', code: '+964' },
  { countryName: 'Ireland', code: '+353' },
  { countryName: 'Israel', code: '+972' },
  { countryName: 'Italy', code: '+39' },
  { countryName: 'Jamaica', code: '+1-876' },
  { countryName: 'Japan', code: '+81' },
  { countryName: 'Jordan', code: '+962' },
  { countryName: 'Kazakhstan', code: '+7' },
  { countryName: 'Kenya', code: '+254' },
  { countryName: 'Kiribati', code: '+686' },
  { countryName: 'Kuwait', code: '+965' },
  { countryName: 'Kyrgyzstan', code: '+996' },
  { countryName: 'Laos', code: '+856' },
  { countryName: 'Latvia', code: '+371' },
  { countryName: 'Lebanon', code: '+961' },
  { countryName: 'Lesotho', code: '+266' },
  { countryName: 'Liberia', code: '+231' },
  { countryName: 'Libya', code: '+218' },
  { countryName: 'Liechtenstein', code: '+423' },
  { countryName: 'Lithuania', code: '+370' },
  { countryName: 'Luxembourg', code: '+352' },
  { countryName: 'Madagascar', code: '+261' },
  { countryName: 'Malawi', code: '+265' },
  { countryName: 'Malaysia', code: '+60' },
  { countryName: 'Maldives', code: '+960' },
  { countryName: 'Mali', code: '+223' },
  { countryName: 'Malta', code: '+356' },
  { countryName: 'Marshall Islands', code: '+692' },
  { countryName: 'Mauritania', code: '+222' },
  { countryName: 'Mauritius', code: '+230' },
  { countryName: 'Mexico', code: '+52' },
  { countryName: 'Micronesia', code: '+691' },
  { countryName: 'Moldova', code: '+373' },
  { countryName: 'Monaco', code: '+377' },
  { countryName: 'Mongolia', code: '+976' },
  { countryName: 'Montenegro', code: '+382' },
  { countryName: 'Morocco', code: '+212' },
  { countryName: 'Mozambique', code: '+258' },
  { countryName: 'Myanmar', code: '+95' },
  { countryName: 'Namibia', code: '+264' },
  { countryName: 'Nauru', code: '+674' },
  { countryName: 'Nepal', code: '+977' },
  { countryName: 'Netherlands', code: '+31' },
  { countryName: 'New Zealand', code: '+64' },
  { countryName: 'Nicaragua', code: '+505' },
  { countryName: 'Niger', code: '+227' },
  { countryName: 'Nigeria', code: '+234' },
  { countryName: 'North Korea', code: '+850' },
  { countryName: 'North Macedonia', code: '+389' },
  { countryName: 'Norway', code: '+47' },
  { countryName: 'Oman', code: '+968' },
  { countryName: 'Pakistan', code: '+92' },
  { countryName: 'Palau', code: '+680' },
  { countryName: 'Palestine', code: '+970' },
  { countryName: 'Panama', code: '+507' },
  { countryName: 'Papua New Guinea', code: '+675' },
  { countryName: 'Paraguay', code: '+595' },
  { countryName: 'Peru', code: '+51' },
  { countryName: 'Philippines', code: '+63' },
  { countryName: 'Poland', code: '+48' },
  { countryName: 'Portugal', code: '+351' },
  { countryName: 'Qatar', code: '+974' },
  { countryName: 'Romania', code: '+40' },
  { countryName: 'Russia', code: '+7' },
  { countryName: 'Rwanda', code: '+250' },
  { countryName: 'Saint Kitts and Nevis', code: '+1-869' },
  { countryName: 'Saint Lucia', code: '+1-758' },
  { countryName: 'Saint Vincent and the Grenadines', code: '+1-784' },
  { countryName: 'Samoa', code: '+685' },
  { countryName: 'San Marino', code: '+378' },
  { countryName: 'Sao Tome and Principe', code: '+239' },
  { countryName: 'Saudi Arabia', code: '+966' },
  { countryName: 'Senegal', code: '+221' },
  { countryName: 'Serbia', code: '+381' },
  { countryName: 'Seychelles', code: '+248' },
  { countryName: 'Sierra Leone', code: '+232' },
  { countryName: 'Singapore', code: '+65' },
  { countryName: 'Slovakia', code: '+421' },
  { countryName: 'Slovenia', code: '+386' },
  { countryName: 'Solomon Islands', code: '+677' },
  { countryName: 'Somalia', code: '+252' },
  { countryName: 'South Africa', code: '+27' },
  { countryName: 'South Korea', code: '+82' },
  { countryName: 'South Sudan', code: '+211' },
  { countryName: 'Spain', code: '+34' },
  { countryName: 'Sri Lanka', code: '+94' },
  { countryName: 'Sudan', code: '+249' },
  { countryName: 'Suriname', code: '+597' },
  { countryName: 'Sweden', code: '+46' },
  { countryName: 'Switzerland', code: '+41' },
  { countryName: 'Syria', code: '+963' },
  { countryName: 'Tajikistan', code: '+992' },
  { countryName: 'Tanzania', code: '+255' },
  { countryName: 'Thailand', code: '+66' },
  { countryName: 'Timor-Leste', code: '+670' },
  { countryName: 'Togo', code: '+228' },
  { countryName: 'Tonga', code: '+676' },
  { countryName: 'Trinidad and Tobago', code: '+1-868' },
  { countryName: 'Tunisia', code: '+216' },
  { countryName: 'Turkey', code: '+90' },
  { countryName: 'Turkmenistan', code: '+993' },
  { countryName: 'Tuvalu', code: '+688' },
  { countryName: 'Uganda', code: '+256' },
  { countryName: 'Ukraine', code: '+380' },
  { countryName: 'United Arab Emirates', code: '+971' },
  { countryName: 'United Kingdom', code: '+44' },
  { countryName: 'United States of America', code: '+1' },
  { countryName: 'Uruguay', code: '+598' },
  { countryName: 'Uzbekistan', code: '+998' },
  { countryName: 'Vanuatu', code: '+678' },
  { countryName: 'Vatican City', code: '+379' },
  { countryName: 'Venezuela', code: '+58' },
  { countryName: 'Vietnam', code: '+84' },
  { countryName: 'Yemen', code: '+967' },
  { countryName: 'Zambia', code: '+260' },
  { countryName: 'Zimbabwe', code: '+263' },
];

export const COUNTRY_NAMES = COUNTRIES.map((country) => country.countryName);
export const COUNTRY_CODES = COUNTRIES.map((country) => ({ countryName: country.countryName, code: country.code }));
